In [27]:
import pandas as pd
import numpy as np

In [28]:

df = pd.read_excel("Zillow_House_Price.xlsx")
df = df.dropna(subset=["timeZone"])
dropable=['contact_recipients','imgSrc','streetAddress','county','timeZone',
           'taxHistory','dateSold','listed_by','brokerageName',
           'description','nearbyHomes','priceHistory','providerListingID', 'currency',
           'listingProvider','openHouseSchedule','cityId','url',
           'zpid','countyId','brokerId','livingAreaUnits','comingSoonOnMarketDate',
           'building','stateId','attributionInfo','homeStatus',
           'homeFacts','datePosted','mortgageZHLRates', 'favoriteCount',
           'favoriteCount','isListedByOwner','mlsid','pageViewCount',
           'buildingId','country','solarPotential','contingentListingType','message',
           'resoFacts.daysOnZillow']
df=df.drop(dropable,axis=1)

In [29]:
df.duplicated().sum()

0

<b>First check for Not usable data</b>

deleteable metadata:
<ul>
<li>contact_recipients</li>
<li>imgSrc</li>
<li>streetAddress</li>
<li>county</li>
<li>timeZone</li>
<li>taxHistory</li>
<li>dateSold</li>
<li>listed_by</li>
<li>brokerageName</li>
<li>description</li>
<li>nearbyHomes</li>
<li>priceHistory</li>
<li>providerListingID</li>
<li>listingProvider</li>
<li>openHouseSchedule</li>
<li>cityId</li>
<li>url</li>
<li>zpid</li>
<li>countyId</li>
<li>brokerId</li>
<li>comingSoonOnMarketDate</li>
<li>building</li>
<li>stateId</li>
<li>attributionInfo</li>
<li>homeStatus</li>
<li>homeFacts</li>
<li>datePosted</li>
<li>mortgageZHLRates</li>
<li>favoriteCount</li>
<li>isListedByOwner</li>
<li>mlsid</li>
<li>pageViewCount</li>
<li>buildingId</li>
<li>solarPotential</li>
<li>contingentListingType</li>
<li>message</li>
<li>resoFacts.daysOnZillow</li>

</ul>

Maybe important data, that i do not know how to handle
<ul>
<li>countyFIPS</li>
<li>city</li>
<li>state</li>
<li>address</li>
<li>zipcode</li>

<li>schools</li>
<li>resoFacts</li>
<li>listingSubType</li>
<li>timeOnZillow</li>
</ul>
NOT VALID JSON, EVEN WITH EXPERIMENTATION, needs a repair library



All the Canadian Buildings are listed with a price of 0, so currency and coutnry is not needed

In [30]:
df.head()

,longitude,countyFIPS,livingAreaValue,monthlyHoaFee,annualHomeownersInsurance,state,yearBuilt,latitude,schools,rentZestimate,...,zipcode,propertyTaxRate,bathrooms,resoFacts,bedrooms,propertyTypeDimension,price,zestimateHighPercent,listingSubType,homeType
0,-149.90807,2020.0,2668.0,NaN,2840,AK,1959.0,61.217308,[{'link': 'https://www.greatschools.org/alaska...,3142.0,...,99501,1.31,2.0,"{'hasAttachedProperty': False, 'frontageType':...",3.0,Single Family,676100,13.0,"{'is_FSBA': False, 'is_comingSoon': False, 'is...",SINGLE_FAMILY
1,-149.90822,2020.0,3179.0,NaN,2934,AK,1961.0,61.217136,[{'link': 'https://www.greatschools.org/alaska...,3113.0,...,99501,1.31,2.0,"{'hasAttachedProperty': False, 'frontageType':...",3.0,Single Family,698600,13.0,"{'is_FSBA': False, 'is_comingSoon': False, 'is...",SINGLE_FAMILY
2,-149.90833,2020.0,3059.0,NaN,4187,AK,1983.0,61.217000,[{'link': 'https://www.greatschools.org/alaska...,4282.0,...,99501,1.31,3.0,"{'hasAttachedProperty': False, 'frontageType':...",4.0,Single Family,996800,14.0,"{'is_FSBA': False, 'is_comingSoon': False, 'is...",SINGLE_FAMILY
4,-149.90834,2020.0,1642.0,NaN,2920,AK,1947.0,61.216720,[{'link': 'https://www.greatschools.org/alaska...,3458.0,...,99501,1.31,2.0,"{'hasAttachedProperty': False, 'frontageType':...",5.0,Single Family,695300,16.0,"{'is_FSBA': False, 'is_comingSoon': False, 'is...",SINGLE_FAMILY
5,-149.90749,NaN,4483.0,NaN,4100,AK,2000.0,61.217120,[{'link': 'https://www.greatschools.org/alaska...,4161.0,...,99501,1.31,4.0,"{'hasAttachedProperty': False, 'frontageType':...",4.0,Condo,976100,24.0,"{'is_FSBA': False, 'is_comingSoon': False, 'is...",CONDO

In [31]:
df.columns

Index(['longitude', 'countyFIPS', 'livingAreaValue', 'monthlyHoaFee',
       'annualHomeownersInsurance', 'state', 'yearBuilt', 'latitude',
       'schools', 'rentZestimate', 'city', 'zestimateLowPercent',
       'mortgageRates', 'address', 'timeOnZillow', 'zestimate', 'livingArea',
       'zipcode', 'propertyTaxRate', 'bathrooms', 'resoFacts', 'bedrooms',
       'propertyTypeDimension', 'price', 'zestimateHighPercent',
       'listingSubType', 'homeType'],
      dtype='object')

<b>Drop because sql doesnt work on reports</b>

In [32]:
uk=['schools','mortgageRates','address','resoFacts','listingSubType']
df=df.drop(uk,axis=1)

#Property type dimension will already be dropped, because it is a 1 to 1 copy of hometype
#living Area Value is a 1 to 1 coyp to living Area
#dropping before the analysis is better then removing na's that take away data from other rows
rd=['propertyTypeDimension','livingAreaValue']
df=df.drop(rd,axis=1)
#ptd = room type
#lav = living area

<h4>Converting and Encoding</h4>

In [33]:
#zip code will prob need to be dropped, and cant be used for ml since its suggesting a hirachical order, wich zip codes dont have (they kinda have a geographical hirachcal order, but i do not think the ml can understand that)

In [34]:
def convert_price(df):
    # Apply the conversion for rows where the currency is 'CAD'
    df.loc[df['currency'] == 'CAD', 'price'] *= 0.74
    return df

# Since most of the hoa fee is 0, ill assume, if Na= 0
df['monthlyHoaFee'] = df['monthlyHoaFee'].fillna(0)

# Extract the "days" from 'timeOnZillow' and convert to float
df['timeOnZillow'] = df['timeOnZillow'].str.extract('(\d+)').astype(float)

In [35]:
# Hometype: Unknow will be counted as Na, sicne there are only 3 we drop them
df = df[df['homeType'] != 'HOME_TYPE_UNKNOWN']

# this makes multiple columns with the variable (Separate for yes/no)
from sklearn.preprocessing import OneHotEncoder
variables = ['homeType']

# use encoder
encoder = OneHotEncoder(sparse_output=False).set_output(transform="pandas")
one_hot_encoded = encoder.fit_transform(df[variables]).astype(int)
df = pd.concat([df,one_hot_encoded],axis=1).drop(columns=variables)

# homeType_TOWNHOUSE is the furthest on the right, it will be dropped
df = df.drop('homeType_TOWNHOUSE', axis=1)

<h4>Missing handeling</h4>

In [36]:
df = df.dropna(subset=["longitude"])
df = df.dropna(subset=["yearBuilt"])
df = df.dropna(subset=["zestimateLowPercent"])
df = df.dropna(subset=["zestimate"])
df = df.dropna(subset=["propertyTaxRate"])
df = df.dropna(subset=["bathrooms"])
df = df.dropna(subset=["bedrooms"])
df = df.dropna(subset=["zestimateHighPercent"])
df = df.dropna(subset=["livingArea"])

#drop all prices that are 0
df = df[df['price'] != 0]

#use backfill to fill countyFIPS
df['countyFIPS'] = df['countyFIPS'].fillna(method='bfill')

# For timeonZillow, you cannot use ffill or bfill since it is put at random, so imma us a distribution fill
# Fill missing values in 'timeOnZillow' using random sampling from the existing non-missing values
df['timeOnZillow'] = df['timeOnZillow'].apply(
    lambda x: np.random.choice(df['timeOnZillow'].dropna()) if pd.isna(x) else x
)

C:\Users\janni\AppData\Local\Temp\ipykernel_12628\3917338967.py:15: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['countyFIPS'] = df['countyFIPS'].fillna(method='bfill')

In [37]:
df

,longitude,countyFIPS,monthlyHoaFee,annualHomeownersInsurance,state,yearBuilt,latitude,rentZestimate,city,zestimateLowPercent,...,bathrooms,bedrooms,price,zestimateHighPercent,homeType_APARTMENT,homeType_CONDO,homeType_LOT,homeType_MANUFACTURED,homeType_MULTI_FAMILY,homeType_SINGLE_FAMILY
0,-149.90807,2020.0,0.0,2840,AK,1959.0,61.217308,3142.0,Anchorage,12.0,...,2.0,3.0,676100,13.0,0,0,0,0,0,1
1,-149.90822,2020.0,0.0,2934,AK,1961.0,61.217136,3113.0,Anchorage,12.0,...,2.0,3.0,698600,13.0,0,0,0,0,0,1
2,-149.90833,2020.0,0.0,4187,AK,1983.0,61.217000,4282.0,Anchorage,12.0,...,3.0,4.0,996800,14.0,0,0,0,0,0,1
4,-149.90834,2020.0,0.0,2920,AK,1947.0,61.216720,3458.0,Anchorage,15.0,...,2.0,5.0,695300,16.0,0,0,0,0,0,1
5,-149.90749,2020.0,0.0,4100,AK,2000.0,61.217120,4161.0,Anchorage,18.0,...,4.0,4.0,976100,24.0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7155,-149.78406,2020.0,28.0,2764,AK,1978.0,61.115010,3903.0,Anchorage,10.0,...,2.5,3.0,658100,10.0,0,0,0,0,0,1
7156,-149.78296,2020.0,28.0,2160,AK,1974.0,61.115078,3562.0,Anchorage,9.0,...,2.0,4.0,514200,9.0,0,0,0,0,0,1
7157,-149.75220,2020.0,45.0,2768,AK,1972.0,61.124302,4917.0,Anchorage,11.0,...,4.5,5.0,659000,12.0,0,0,0,0,0,1
7158,-149.75658,2020.0,45.0,2979,AK,1972.0,61.124546,4130.0,Anchorage,9.0,...,3.0,5.0,709400,9.0,0,0,0,0,0,1
7159,-149.75730,2020.0,45.0,2410,AK,1974.0,61.124630,3566.0,Anchorage,9.0,...,2.5,4.0,573900,10.0,0,0,0,0,0,1

In [38]:
df.isna().sum()

longitude                    0
countyFIPS                   0
monthlyHoaFee                0
annualHomeownersInsurance    0
state                        0
yearBuilt                    0
latitude                     0
rentZestimate                0
city                         0
zestimateLowPercent          0
timeOnZillow                 0
zestimate                    0
livingArea                   0
zipcode                      0
propertyTaxRate              0
bathrooms                    0
bedrooms                     0
price                        0
zestimateHighPercent         0
homeType_APARTMENT           0
homeType_CONDO               0
homeType_LOT                 0
homeType_MANUFACTURED        0
homeType_MULTI_FAMILY        0
homeType_SINGLE_FAMILY       0
dtype: int64

<b>The data is now reportable</b>

In [39]:
df.duplicated().sum()

0

In [40]:
# Save the DataFrame to a CSV file
# To put it into the Report.ipynb 
df.to_csv('Clean_Zillow.csv', index=False)